### ISSUE TITLE
Chapter titles in contents page

### ISSUE THREAD

**Issue by zikalify** [standardebooks/thomas-a-kempis_the-imitation-of-christ_william-benham#5]
I feel like this book would be better if each of the chapter headings was included in the contents page making it easier to jump around the book. The headings are included in the content page on the Gutenberg version but not this one.

**Comment by acabal** [comment]
The headings are classified as bridgeheads and not subtitles, so they don't appear in the ToC. There are no plans to change that at the moment, sorry.
